//! Merkle leaf and proof verification, byte-for-byte the same as packages/core/src/merkle.ts.
//!
//! leaf = keccak256(0x00 || action_id[32] || wallet[32] || mint[32] || snapshot_slot u64 LE || entitlement u64 LE)
//! node = keccak256(0x01 || min(a, b) || max(a, b))
//! Odd nodes are promoted, so a proof is just the list of siblings from the leaf upwards.

use anchor_lang::prelude::Pubkey;
use solana_keccak_hasher::hashv;

pub const LEAF_PREFIX: u8 = 0x00;
pub const NODE_PREFIX: u8 = 0x01;
pub const MAX_PROOF_LEN: usize = 32;

pub fn leaf_hash(action_id: &[u8; 32], wallet: &Pubkey, mint: &Pubkey, snapshot_slot: u64, entitlement: u64) -> [u8; 32] {
    hashv(&[
        &[LEAF_PREFIX],
        action_id,
        wallet.as_ref(),
        mint.as_ref(),
        &snapshot_slot.to_le_bytes(),
        &entitlement.to_le_bytes(),
    ])
    .to_bytes()
}

pub fn node_hash(a: &[u8; 32], b: &[u8; 32]) -> [u8; 32] {
    let (lo, hi) = if a <= b { (a, b) } else { (b, a) };
    hashv(&[&[NODE_PREFIX], lo, hi]).to_bytes()
}

pub fn verify(leaf: [u8; 32], proof: &[[u8; 32]], root: &[u8; 32]) -> bool {
    if proof.len() > MAX_PROOF_LEN {
        return false;
    }
    let mut node = leaf;
    for sibling in proof {
        node = node_hash(&node, sibling);
    }
    &node == root
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;

    /// Vectors from fixtures/merkle.json (generated by packages/core, `pnpm merkle:vectors`).
    #[test]
    fn matches_typescript_vectors() {
        let json: serde_json::Value = serde_json::from_str(include_str!("../../../fixtures/merkle.json")).unwrap();
        let action_id: [u8; 32] = hex::decode(json["actionId"].as_str().unwrap()).unwrap().try_into().unwrap();
        let mint = Pubkey::from_str(json["mint"].as_str().unwrap()).unwrap();
        let slot: u64 = json["snapshotSlot"].as_str().unwrap().parse().unwrap();
        let root: [u8; 32] = hex::decode(json["root"].as_str().unwrap()).unwrap().try_into().unwrap();
        for leaf in json["leaves"].as_array().unwrap() {
            let wallet = Pubkey::from_str(leaf["wallet"].as_str().unwrap()).unwrap();
            let entitlement: u64 = leaf["entitlement"].as_str().unwrap().parse().unwrap();
            let expected_leaf: [u8; 32] = hex::decode(leaf["leaf"].as_str().unwrap()).unwrap().try_into().unwrap();
            let computed = leaf_hash(&action_id, &wallet, &mint, slot, entitlement);
            assert_eq!(computed, expected_leaf, "leaf for {wallet}");
            let proof: Vec<[u8; 32]> = leaf["proof"]
                .as_array()
                .unwrap()
                .iter()
                .map(|p| hex::decode(p.as_str().unwrap()).unwrap().try_into().unwrap())
                .collect();
            assert!(verify(computed, &proof, &root), "proof for {wallet}");
            assert!(!verify(computed, &proof, &[0u8; 32]));
        }
    }

    #[test]
    fn rejects_long_proofs() {
        let leaf = [1u8; 32];
        let proof = vec![[2u8; 32]; 33];
        assert!(!verify(leaf, &proof, &leaf));
    }
}
