import { chromium } from "@playwright/test";
const base = "http://localhost:3000";
const b = await chromium.launch(); const page = await b.newPage({ viewport: { width: 1280, height: 900 }, deviceScaleFactor: 2 });
const list = await (await page.request.get(base + "/api/actions")).json();
const act = list.actions.find((a) => a.snapshot && a.onchain && a.kind === "distribution") ?? list.actions.find((a) => a.snapshot);
const clip = { x: 240, y: 0, width: 1040, height: 780 };
await page.goto(base + "/portfolio?demo=1", { waitUntil: "networkidle" });
await page.locator("table.table").first().waitFor({ timeout: 60000 });
await page.waitForTimeout(1200);
await page.screenshot({ path: "public/frames/portfolio.png", clip });
await page.goto(base + `/issuer?demo=1&action=${act.id}&step=3`, { waitUntil: "networkidle" });
await page.locator(".bar").first().waitFor({ timeout: 60000 });
await page.waitForTimeout(800);
await page.screenshot({ path: "public/frames/issuer.png", clip });
await page.goto(base + `/actions/${act.id}`, { waitUntil: "networkidle" });
await page.locator(".proof").first().waitFor({ timeout: 60000 });
await page.waitForTimeout(800);
await page.screenshot({ path: "public/frames/record.png", clip });
console.log("frames done", act.id);
await b.close();
